### ISSUE TITLE
Freeze when processing large quantity of "skipping unchanged chapter"

### ISSUE THREAD

**Issue by BraveDude8** [Xnot/mangadex-mass-uploader#8]
Actually making edits is fine, but if it's skipping a bunch of chapters that don't need changes it'll freeze up entirely while it checks.

**Comment by Xnot** [comment]
Pretty sure this is just kivy being laggy when there is a lot of shit in the text box to render. One possible solution is to limit the maximum number of lines in the log to 50 or so, tho that means you won't by able scroll all the way up to see old errors.

**Comment by Xnot** [comment]
fixed in 2.5.2 probably
